= Vaadin, Spring, Kotlin - the super easy approach to build modern web apps on JVM

This is an example project how to build a simple CRUD app with Kotlin, Spring (Boot & Data JPA) and Vaadin. The example built on top of the end result of https://spring.io/guides/gs/crud-with-vaadin/[the Vaadin guide in spring.io]. The only difference is that this project uses Kotlin for most code.

The example app also uses https://github.com/mvysny/karibu-dsl[Karibu-DSL (Vaadin Kotlin Extensions)] to make the UI code feel more native in terms of Kotlin usage.

== Trying it out

To start the project, just type this into your terminal:

$ git clone https://github.com/mvysny/gs-crud-with-vaadin
$ cd gs-crud-with-vaadin
$ ./gradlew bootRun

The app is now running on http://localhost:8080

You can also run the project by Maven: just execute "mvn spring-boot:run". Most probably you'll want to just import it to your favourite IDE and start playing around with it!

Feel free to use it as a basis of your next project and propose improvements (issues or pull requests) to both this example or to Karibu-DSL.
